<?php

namespace AppBundle\Repository;

/**
 * publishedPicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publishedPicsRepository extends \Doctrine\ORM\EntityRepository
{
}
