<?php

namespace AppBundle\Repository;

/**
 * unpublishedPicsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class unpublishedPicsRepository extends \Doctrine\ORM\EntityRepository
{
}
