unpublishedpics_index:
    path:     /
    defaults: { _controller: "AppBundle:unpublishedPics:index" }
    methods:  GET

unpublishedpics_show:
    path:     /{id}/show
    defaults: { _controller: "AppBundle:unpublishedPics:show" }
    methods:  GET

unpublishedpics_new:
    path:     /new
    defaults: { _controller: "AppBundle:unpublishedPics:new" }
    methods:  [GET, POST]

unpublishedpics_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBundle:unpublishedPics:edit" }
    methods:  [GET, POST]

unpublishedpics_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBundle:unpublishedPics:delete" }
    methods:  DELETE
