unpublishedpics:
    resource: "@AppBundle/Resources/config/routing/unpublishedpics.yml"
    prefix:   /unpublishedpics

home:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET

lastpublishedpics:
    path: /lastpublishedpics
    defaults: { _controller: "AppBundle:unpublishedPics:fiveLastPhotos" }
    methods: GET

loadeightfollowingpics:
    path: /loadfollowingpics/{lastpic}
    defaults: { _controller: "AppBundle:unpublishedPics:FollowingPhotos" }
    methods: GET